### ISSUE TITLE
Feedback zur Pipeline

### ISSUE THREAD

**Issue by hupling** [it-at-m/.github#18]
@simonhir bitte die Änderungen an der Pipeline von https://github.com/it-at-m/refarch hier nochmal erklären. Damit wir schauen können, ob wir das nicht auch zentral einpflegen können. Vielleicht hast du an der ein oder anderen Stelle bessere Ideen wie ich.

**Comment by simonhir** [comment]
Der Grund wieso ich abgewichen bin ist hauptsächlich, dass in jedem MR das komplette Repo gebaut und getestet wird.
Wenn der Release aber die Eingabe einen speziellen Moduls benötigt kann man das nicht wieder verwenden.

Nachfolgend wären mal so die Punkte die unter Anderem im Rahmen von DigiWF aufgetreten sind und als sinnvoll empfunden wurden:
- Bauen von dev Image auf Default-Branch
- Version Bump (Hier per Maven Release)
  - Was man beachten muss ist, dass der Release nach Maven Central recht lange dauern kann
  - Außerdem soll der Version-Bump nur bei einem Release und nicht bei der MR CI gemacht werden
- Automatisches erstellen der Release-Beschreibung

Umgesetzt ist das jetzt im Refarch-Repo ähnlich wie bei DigiWF:
- Der Maven-Build akzeptiert als Argument ob es ein Snapshot-Release ist
  - Wenn ja kein Version-Bump (einfaches Bauen via `mvn clean install`)
- Der Maven-Build akzeptiert als Argument ob Images gebaut werden sollen
  - Wird dann neben dem manuellen Release auch auf dem Default Branch auf `true` gesetzt
- Zwei einzelne Workflows für `build` und `release`, die jeweils den Maven-Build mit den entsprechenden Argumenten aufrufen

Der Stand im Refach-Repo muss bezüglich Release noch getestet werden, denke aber, dass es da nur zu kleinen Anpassungen kommt, das vom obigen Ablauf her aber gleich bleibt.

**Comment by hupling** [comment]
* Bauen von dev Image auf Default-Branch
    * Also vielleicht ist das sinnvoll normalerweise auf dev zu taggen und nur bei Release auf latest. Kannst du es ändern?
* Version Bump (Hier bereits eingebaut per Maven Release) 
    * Wir pushen nicht auf MavenCentral. Kannst du es ncoh einbauen? `mvn release:prepare` ` mvn release:perform` ausgeführt wird finde ich auch nicht toll. Da wird dann etwas zweimal Compeliert, um die richtige Versionsnummer zu haben. Beim DigiWf hat mich gestört, dass ihr nicht die pom zurück in das Repo pusht. 
* Release und nicht bei der MR CI
    * das verstehe ich nicht. Ein Maven Release ist doch bei uns einfach ein manuell getriggerter Schritt
* Automatisches erstellen der Release-Beschreibung
    * Das hätte ich auch gern, aber wüsste keine Weg wie es umgesetzt werden kann. Wenn ich Frontend und Backend getrennt releasen will, dann sollen auch unterschiedliche Release Notes generiert werden. Wenn jetzt Frontend und Backend gemeinsam released werden sollen, dann muss ich nochmal schauen, wie man generisch Images bauen kann (vermutlich mit Matrixen) Außerdem ist es auch schwierig, wenn Frontend und Backend unterschiedlich Java-Versionen haben. 
*   Code-Coverage via Codecov 
    * Finde ich gut zum einbauen. Im internen Gitlab habe ich es immer noch nicht geschafft, dass es gescheit funktioniert.
* Der Maven-Build akzeptiert als Argument ob es ein Snapshot-Release ist  
    * es wird einfach bei jedem push im jeweiligen Ordner ein mvn release ausgeführt. 
* Der Maven-Build akzeptiert als Argument ob Images gebaut werden sollen 
    * Image  werden immer beim main-Branch und beim Release gebaut. Das irgendwie ausschalten macht für mich keinen Sinn
* Zwei einzelne Workflows für build und release, die jeweils den Maven-Build mit den entsprechenden Argumenten aufrufe
    *  was für maven Argumente braucht ihr noch

**Comment by hupling** [comment]
@ejcsid oder @banzuu  habt ihr noch Anmerkungen?

**Comment by simonhir** [comment]
> Also vielleicht ist das sinnvoll normalerweise auf dev zu taggen und nur bei Release auf latest. Kannst du es ändern?

Im Refarch-Projekt sollte das so umgesetzt sein, kann man nach dem ersten erfolgreichen Release dann bei Bedarf übernehmen.

> Wir pushen nicht auf MavenCentral. Kannst du es ncoh einbauen?

Das wird über die Projekt-Pom gesteuert siehe interne Doku: https://git.muenchen.de/ccse/ospo/-/wikis/Maven-Central

> Beim DigiWf hat mich gestört, dass ihr nicht die pom zurück in das Repo pusht.

Machen wir in einem extra Schritt, aber ist eher eine Altlast meiner Meinung nach macht das mit Maven-Release wie hier schon mehr Sinn.

> es wird einfach bei jedem push im jeweiligen Ordner ein mvn release ausgeführt.

> Image werden immer beim main-Branch und beim Release gebaut. Das irgendwie ausschalten macht für mich keinen Sinn

Wenn du aber ein Maven Template für Release, Image-Build auf dev/main und Test-Build in der CI nutzen willst kommst du nicht darum rum zwei Parameter z.B. eben Snapshot-Build (true/false) und Build-Images (true/false) einzuführen.

**Comment by ejcsid** [comment]
> @ejcsid oder @banzuu habt ihr noch Anmerkungen?

Beim Aufruf von https://github.com/it-at-m/refarch bekomme ich einen 404. Ist das ein privates Projekt?

**Comment by simonhir** [comment]
> Ist das ein privates Projekt

Ja, weil sich das aktuell noch im Aufbau befindet

**Comment by ejcsid** [comment]
@simonhir kannst du @ejcsid und @banzuu zu dem Projekt refarch hinzufügen, damit wir die Pipeline anschauen können? Danke!

**Comment by simonhir** [comment]
@ejcsid sollte erledigt sein

**Comment by simonhir** [comment]
Repo ist jetzt open source und zumindest das bauen auf Dev lief erfolgreich.
Einziger offener Test ist jetzt noch ein Release

**Comment by simonhir** [comment]
Was mir auch gerade noch aufgefallen ist, dass in einigen Projekten der Default-Branch keine Pushes erlaubt, was dann beim Maven-Release Probleme macht.
Hab im refarch-Repo das auch mal als PR anstatt direktem Push umgesetzt.

**Comment by hupling** [comment]
Feedback Treffen:

Pipeline:

- pom.xml auf parent ebene.
- node js auslagern.

**Comment by hupling** [comment]
>  pom.xml auf parent ebene.

Nachteil es können nicht unterschiedliche Java Versionen verwendet werden.

**Comment by ejcsid** [comment]
>> pom.xml auf parent ebene.
>
> Nachteil es können nicht unterschiedliche Java Versionen verwendet werden.

Kann glaub ich mit Maven Toolchains gelöst werden: https://maven.apache.org/guides/mini/guide-using-toolchains.html

**Comment by hupling** [comment]
@devtobi meinte:
- Einen Action.yml  mit Matrix
- Maven Release nur für Libraries, sonst Github-Release

**Comment by hupling** [comment]
# npm Release (auch nur für Libraries interessant)

- entweder mit `npm version <update_type>` und `npm publish`
- oder  `npm run semantic-release`

**Comment by hupling** [comment]
Ticket wird hier weitergeführt https://github.com/it-at-m/.github/issues/41
